// Auto-generated temporary shims for missing third-party modules to unblock TypeScript
// Replace these with real packages / types as a follow-up.

declare module '@radix-ui/react-accordion'
declare module '@radix-ui/react-alert-dialog'
declare module '@radix-ui/react-aspect-ratio'
declare module '@radix-ui/react-avatar'
declare module 'react-day-picker'
declare module 'embla-carousel-react'
declare module 'recharts'
declare module '@radix-ui/react-checkbox'
declare module '@radix-ui/react-collapsible'
declare module 'cmdk'
declare module '@radix-ui/react-context-menu'
declare module 'vaul'
declare module '@radix-ui/react-dropdown-menu'
declare module 'react-hook-form'
declare module '@radix-ui/react-hover-card'
declare module 'input-otp'
declare module '@radix-ui/react-menubar'
declare module '@radix-ui/react-navigation-menu'
declare module '@radix-ui/react-popover'
declare module '@radix-ui/react-progress'
declare module '@radix-ui/react-radio-group'
declare module 'react-resizable-panels'
declare module '@radix-ui/react-scroll-area'
declare module '@radix-ui/react-select'
declare module '@radix-ui/react-separator'
declare module '@radix-ui/react-slider'
declare module 'sonner'
declare module '@radix-ui/react-switch'
declare module '@radix-ui/react-tabs'
declare module '@radix-ui/react-toast'
declare module '@radix-ui/react-toggle-group'
declare module '@radix-ui/react-toggle'
declare module '@radix-ui/react-tooltip'
declare module 'cmdk'
declare module 'input-otp'
declare module 'react-resizable-panels'

// Some other utilities
declare module '@google/genai'
declare module '@heroui/avatar'
declare module '@heroui/date-picker'
declare module '@heroui/system'
declare module '@heroui/theme'
declare module '@heroui/toast'

// Allow importing image file types if needed
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.webp'
declare module '*.svg'
